### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by ghost** [silinternational/idp-profile-ui#63] opened 2021-03-04 16:28 UTC
Don't make people scroll to see the "next" option. A surprising number of people don't think to do that. 
https://www.nngroup.com/articles/scrolling-and-attention/
My screen res is 1920x1080
![image](https://user-images.githubusercontent.com/78667382/109995580-6b503500-7cdc-11eb-843d-29c6a110a7a5.png)
![image](https://user-images.githubusercontent.com/78667382/109995827-a5213b80-7cdc-11eb-90ae-f569b5bedc10.png)

**Comment by hobbitronics** [comment] 2022-07-11 00:52
I can't seem to reproduce this. I tried simulating 1920X1080 and got this 
![image](https://user-images.githubusercontent.com/70765247/178169626-9a3068bb-9739-494f-ba97-bd6b0f5dc7cc.png)
Possibly your browser was zoomed?

It possibly would be better if we rearranged the layout so the button stays on screen regardless of zoom.

**Comment by devon-sil** [comment] 2024-06-11 00:31
Unable to reproduce and not enough time to try to hunt more.  Since this is a ghost user, it won't be possible to gather more details.  Closing.

**Closed by devon-sil** 2024-06-11 00:31 UTC
